name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js and pnpm
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: pnpm install

    - name: TypeScript Typecheck
      run: pnpm run typecheck

    - name: Run Lint
      run: pnpm run lint
