name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/actions/setup-pnpm@v1
      with:
        version: 6.0.2

    - name: Install Dependencies
      run: pnpm install

    - name: TypeScript Typecheck
      run: pnpm run typecheck

    - name: Run Lint
      run: pnpm run lint
